### ISSUE TITLE
Use environment variables for host ip (and port maybe)

### ISSUE THREAD

**Issue by asurinsaka** [Dhruvgera/LocalAI-frontend#1]
Hi, the host ip is hard coded as local host. 
Could you please move that to environment variable?
It will be more flexible to use the front end. 

Thanks for the greate project!

**Comment by Dhruvgera** [comment]
> Hi, the host ip is hard coded as local host. Could you please move that to environment variable? It will be more flexible to use the front end.
> 
> Thanks for the greate project!

Sure! I would update to use env variable

**Comment by EchedeyLR** [comment]
I have made some local changes to prepare it for production including this one.

Check whenever you have some time. I will by using this in my own production environment.
